name: Auto deploy bankdash 

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BANKDASH_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BANKDASH_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BANKDASH_AZURE_SUBSCRIPTION_ID }}

      - name: Build and deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: DefaultResourceGroup-EUS
          containerAppName: bankdash
          sourcePath: .
